language: python
sudo: false
python:
 - 2.6
 - 2.7
 - 3.3
 - 3.4
 - 3.5
env:
 - DJANGO='django>=1.3,<1.4'
 - DJANGO='django>=1.4,<1.5'
 - DJANGO='django>=1.5,<1.6'
 - DJANGO='django>=1.6,<1.7'
 - DJANGO='django>=1.7,<1.8'
 - DJANGO='django>=1.8,<1.9'
install:
 - pip install $DJANGO django-classy-tags pep8 backport-collections
script: python runtests.py
notifications:
  email: false
matrix:
  exclude:
    - python: 2.6
      env: DJANGO='django>=1.7,<1.8'
    - python: 2.6
      env: DJANGO='django>=1.8,<1.9'
    - python: 3.3
      env: DJANGO='django>=1.3,<1.4'
    - python: 3.3
      env: DJANGO='django>=1.4,<1.5'
    - python: 3.4
      env: DJANGO='django>=1.3,<1.4'
    - python: 3.4
      env: DJANGO='django>=1.4,<1.5'
    - python: 3.5
      env: DJANGO='django>=1.3,<1.4'
    - python: 3.5
      env: DJANGO='django>=1.4,<1.5'
